### ISSUE TITLE
Rewrite engine beginner mistake - slide 13

### ISSUE THREAD

**Issue by Zulcom** [stevegrunwell/wordpress-git#2]
Hello Steve, i want to tell story for you
I read your advice on slide 13 (http://stevegrunwell.github.io/wordpress-git/#/13)
and append your code to end of my .htaccess file
After 5 hours of exhausting debugging apache, i understood: Your code should be added BEFORE WordPress default rule:
```
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
</IfModule>
```
Otherwise he just does not do anything.
I guess it's somehow related to the standard Wordpress rule, but I'm not sure.
If I'm wrong, I'll be glad to hear from you how this works.
So i ask you to add some warning for other beginners so that they can save their time and calmness.
Thanks for trying to understand my bad english

**Comment by stevegrunwell** [comment]
Муравьёв,

You’re not the first person to have questions about the slide deck — I haven’t given that talk for almost 3 years, and there’s a lot of context missing when compared to the corresponding blog post <https://stevegrunwell.com/blog/keeping-wordpress-under-version-control-with-git/>. I’ve updated the slide deck on GitHub Pages to include a link back to the blog post so other devs will be saved the time you spent trying to decode slides.

I’ve been planning an update to the blog post for some time with a new version (short version: don’t put WordPress Core under version control, and load plugins via WPackagist <https://wpackagist.org/>. Maybe some day :)

Thanks for reaching out, and sorry for the less-than-obvious answers from the slides!

-Steve
